#!/bin/sh

openPrefs() {
  if [ "$(which gnome-extensions)" ]
  then
    gnome-extensions prefs $1
  else
    gdbus call --session \
      --dest=org.gnome.Shell.Extensions \
      --object-path=/org/gnome/Shell/Extensions \
      --method=org.gnome.Shell.Extensions.OpenExtensionPrefs $1 '' '{}'
  fi
}

UUID=$1

if [ "$UUID" ]
then
  openPrefs $UUID
else
  gapplication launch org.gnome.Extensions
fi
